rename rancher to ranger

diff --git a/scripts/check-release-images-exist b/scripts/check-release-images-exist
--- a/scripts/check-release-images-exist
+++ b/scripts/check-release-images-exist
@@ -11,19 +11,19 @@ cd ./..
 TEMP_FILE=$(mktemp)
 
 if [ -n "${DRONE_TAG}" ]; then
-  if [ -s ./bin/rancher-images.txt ]; then
-    # We skip rancher/rancher and rancher/rancher-agent because the manifest for these gets created later in the pipeline
-    for rancherimage in $(cat ./bin/rancher-images.txt | egrep -v "^rancher/rancher:|^rancher/rancher-agent:"); do
-      echo "INFO: Checking if image [${rancherimage}] exists"
-      if ! skopeo inspect "docker://${rancherimage}" >/dev/null; then
-        echo "ERROR: Image [${rancherimage}] does not exist"
-        echo "${rancherimage}" >> $TEMP_FILE
+  if [ -s ./bin/ranger-images.txt ]; then
+    # We skip ranger/ranger and ranger/ranger-agent because the manifest for these gets created later in the pipeline
+    for rangerimage in $(cat ./bin/ranger-images.txt | egrep -v "^ranger/ranger:|^ranger/ranger-agent:"); do
+      echo "INFO: Checking if image [${rangerimage}] exists"
+      if ! skopeo inspect "docker://${rangerimage}" >/dev/null; then
+        echo "ERROR: Image [${rangerimage}] does not exist"
+        echo "${rangerimage}" >> $TEMP_FILE
       else
-        echo "OK: Image [${rancherimage}] does exist"
+        echo "OK: Image [${rangerimage}] does exist"
       fi
     done
   else
-    echo "ERROR: ./bin/rancher-images.txt does not exist or is empty"
+    echo "ERROR: ./bin/ranger-images.txt does not exist or is empty"
     exit 1
   fi
 
diff --git a/scripts/provisioning-tests b/scripts/provisioning-tests
--- a/scripts/provisioning-tests
+++ b/scripts/provisioning-tests
@@ -8,7 +8,7 @@ cleanup()
 {
     EXIT=$?
     set +ex
-    echo Stopping rancher server
+    echo Stopping ranger server
     kill $RANCHER_RUN_PID
     wait $RANCHER_RUN_PID
     if [ $PID != -1 ]; then
@@ -20,7 +20,7 @@ cleanup()
 
 cd $(dirname $0)/..
 
-TB_ORG=rancher
+TB_ORG=ranger
 
 if [ -z "${V2PROV_TEST_DIST}" ] || [ "${V2PROV_TEST_DIST}" = "k3s" ]; then
   V2PROV_TEST_DIST=k3s
@@ -48,29 +48,29 @@ eval "$(grep '^ENV CATTLE_KDM_BRANCH' package/Dockerfile | awk '{print "export "
 if [ -z "${SOME_K8S_VERSION}" ]; then
 # Get the last release for $DIST, which is usually the latest version or an experimental version.
 # Previously this would use channels, but channels no longer reflect the latest version since
-# https://github.com/rancher/rancher/issues/36827 has added appDefaults. We do not use appDefaults
+# https://github.com/ranger/ranger/issues/36827 has added appDefaults. We do not use appDefaults
 # here for simplicity's sake, as it requires semver parsing & matching. The last release should
 # be good enough for our needs.
-export SOME_K8S_VERSION=$(curl -sS https://raw.githubusercontent.com/rancher/kontainer-driver-metadata/dev-v2.7/data/data.json | jq -r ".$DIST.releases[-1].version")
+export SOME_K8S_VERSION=$(curl -sS https://raw.githubusercontent.com/ranger/kontainer-driver-metadata/dev-v2.7/data/data.json | jq -r ".$DIST.releases[-1].version")
 fi
 
-echo "Starting rancher server for provisioning-tests using $SOME_K8S_VERSION"
-touch /tmp/rancher.log
+echo "Starting ranger server for provisioning-tests using $SOME_K8S_VERSION"
+touch /tmp/ranger.log
 
-mkdir -p /var/lib/rancher/$DIST/agent/images
-grep PodTestImage ./tests/v2prov/defaults/defaults.go | cut -f2 -d'"' > /var/lib/rancher/$DIST/agent/images/pull.txt
-grep MachineProvisionImage ./pkg/settings/setting.go | cut -f4 -d'"' >> /var/lib/rancher/$DIST/agent/images/pull.txt
-mkdir -p /usr/share/rancher/ui/assets
-curl -sLf https://github.com/rancher/system-agent/releases/download/${CATTLE_SYSTEM_AGENT_VERSION}/rancher-system-agent-amd64 -o /usr/share/rancher/ui/assets/rancher-system-agent-amd64
-curl -sLf https://github.com/rancher/system-agent/releases/download/${CATTLE_SYSTEM_AGENT_VERSION}/system-agent-uninstall.sh -o /usr/share/rancher/ui/assets/system-agent-uninstall.sh
+mkdir -p /var/lib/ranger/$DIST/agent/images
+grep PodTestImage ./tests/v2prov/defaults/defaults.go | cut -f2 -d'"' > /var/lib/ranger/$DIST/agent/images/pull.txt
+grep MachineProvisionImage ./pkg/settings/setting.go | cut -f4 -d'"' >> /var/lib/ranger/$DIST/agent/images/pull.txt
+mkdir -p /usr/share/ranger/ui/assets
+curl -sLf https://github.com/ranger/system-agent/releases/download/${CATTLE_SYSTEM_AGENT_VERSION}/ranger-system-agent-amd64 -o /usr/share/ranger/ui/assets/ranger-system-agent-amd64
+curl -sLf https://github.com/ranger/system-agent/releases/download/${CATTLE_SYSTEM_AGENT_VERSION}/system-agent-uninstall.sh -o /usr/share/ranger/ui/assets/system-agent-uninstall.sh
 
-run_rancher()
+run_ranger()
 {
     RESTART_COUNT=0
     while sleep 2; do
         if [ "$PID" != "-1" ] && [ ! -e /proc/$PID ]; then
-            echo Rancher died
-            dump_rancher_logs
+            echo Ranger died
+            dump_ranger_logs
             echo K3s logs were:
             echo -e "-----K3S-LOG-DUMP-START-----"
             cat build/testdata/k3s.log | gzip | base64 -w 0
@@ -81,43 +81,43 @@ run_rancher()
             set -e
             PID=-1
             if [ "$RESTART_COUNT" = "2" ]; then
-                echo Rancher died 3 times, aborting
+                echo Ranger died 3 times, aborting
                 kill -42 $PWRAPPROC
             fi
             RESTART_COUNT=$((RESTART_COUNT + 1))
             sleep 5
         fi
         if [ "$PID" = "-1" ]; then
-          echo Starting rancher server using run
-          ./scripts/run >/tmp/rancher.log 2>&1 &
+          echo Starting ranger server using run
+          ./scripts/run >/tmp/ranger.log 2>&1 &
           PID=$!
         fi
         sleep 2
     done
 }
 
-dump_rancher_logs()
+dump_ranger_logs()
 {
-  echo Rancher logs were
+  echo Ranger logs were
   echo -e "-----RANCHER-LOG-DUMP-START-----"
-  cat /tmp/rancher.log | gzip | base64 -w 0
+  cat /tmp/ranger.log | gzip | base64 -w 0
   echo -e "\n-----RANCHER-LOG-DUMP-END-----"
 }
 
 # uncomment to get startup logs. Don't leave them on because it slows drone down too
 # much
-#tail -F /tmp/rancher.log &
+#tail -F /tmp/ranger.log &
 #TPID=$!
 
 trap "exit 1" 42
 PWRAPPROC="$$"
 
 PID=-1
-run_rancher &
+run_ranger &
 RANCHER_RUN_PID=$!
 trap cleanup exit
 
-echo Sleeping for 5 seconds before checking Rancher health
+echo Sleeping for 5 seconds before checking Ranger health
 sleep 5
 
 while ! curl -sf http://localhost:8080/ping; do
@@ -128,15 +128,15 @@ done
 echo ""
 
 rwWC=0
-echo "Waiting up to 5 minutes for rancher-webhook deployment"
-while ! kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml rollout status -w -n cattle-system deploy/rancher-webhook &>/dev/null; do
+echo "Waiting up to 5 minutes for ranger-webhook deployment"
+while ! kubectl --kubeconfig /etc/ranger/k3s/k3s.yaml rollout status -w -n cattle-system deploy/ranger-webhook &>/dev/null; do
   if [[ "$rwWC" == 150 ]]; then
-    echo "rancher-webhook was not available within 5 minutes. failing fast"
-    dump_rancher_logs
+    echo "ranger-webhook was not available within 5 minutes. failing fast"
+    dump_ranger_logs
     exit 1
   fi
   if [[ $((rwWC%30)) == 0 ]] && [[ "$rwWC" != "0" ]]; then
-    echo "rancher-webhook was not ready within $((rwWC/30)) minutes"
+    echo "ranger-webhook was not ready within $((rwWC/30)) minutes"
   fi
     sleep 2
     rwWC=$((rwWC + 1))
@@ -145,5 +145,5 @@ done
 
 echo Running provisioning-tests $RUNARG
 
-export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
-go test $RUNARG -v -failfast -timeout 60m ./tests/v2prov/tests/... || dump_rancher_logs
+export KUBECONFIG=/etc/ranger/k3s/k3s.yaml
+go test $RUNARG -v -failfast -timeout 60m ./tests/v2prov/tests/... || dump_ranger_logs
